routes/admin.php
<?php


use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\EquipmentController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShiftController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

// GENERAL & AUTOCOMPLETE ROUTES
Route::get('/',                  [HomeController::class, 'dashboard'])
    ->name('dashboard');

Route::get('/search',            [HomeController::class, 'search'])
    ->name('search');

Route::post('/create-shift',       [ShiftController::class, 'create-shift'])->name('create-shift');

Route::get('/usersAutoComplete',    [UserController::class, 'usersAutoComplete'])
    ->name('usersAutoComplete');

Route::get('/citiesAutoComplete',   [CityController::class, 'citiesAutoComplete'])
    ->name('citiesAutoComplete');

Route::get('/supplierAutoComplete', [AdminController::class, 'supplierAutoComplete'])
    ->name('supplierAutoComplete');

Route::get('remove-images',         [EquipmentController::class, 'removeImage'])->name('removeImage');

Route::prefix('datatables')->name('datatables.')->group(function () {

    Route::post('/getEquipments',   [EquipmentController::class, 'getEquipments'])
        ->name('getEquipments');

    Route::post('/getAdmins',       [AdminController::class, 'getAdmins'])
        ->name('getAdmins');

    Route::post('/getCategories',   [CategoryController::class, 'getCategories'])
        ->name('getCategories');

    Route::post('/getShifts',        [ShiftController::class, 'getShifts'])
        ->name('getShifts');

    Route::post('/getContacts',     [ContactController::class, 'getContacts'])
        ->name('getContacts');

    Route::post('/getUsers',        [UserController::class, 'getUsers'])
        ->name('getUsers');

    Route::post('/getCities',       [CityController::class, 'getCities'])
        ->name('getCities');

    Route::GET('/setStatus/{order}',[AdminController::class, 'setStatus'])
        ->name('setStatus');
});

Route::prefix('orders')->name('orders.')->group(function (){
    Route::POST('/getOrders',            [OrderController::class, 'getOrders'])->name('getOrders');
    Route::GET('/',                      [OrderController::class, 'index'])->name('index');
    Route::GET('/{order}',               [OrderController::class, 'show'])->name('show');
    Route::GET('/setOrderStatus/{id}',   [OrderController::class, 'setOrderStatus'])->name('setOrderStatus');
    Route::GET('/setOrderBranch/{order}',[OrderController::class, 'setOrderBranch'])->name('setOrderBranch');
});

Route::resource('settings',       SettingController::class);
Route::resource('categories',     CategoryController::class);
Route::resource('users',          UserController::class);
Route::resource('orders',         OrderController::class);
Route::resource('shifts',         ShiftController::class);
Route::resource('admins',         AdminController::class);
Route::resource('cities',         CityController::class);
Route::resource('roles',          RoleController::class);
Route::resource('equipment',      EquipmentController::class);
Route::resource('contacts',       ContactController::class);

routes/user.php
<?php


use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
|
| Here is where you can register user routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "user" middleware group. Now create something great!
|
*/
// GENERAL
Route::get('/citiesAutoComplete', [HomeController::class, 'citiesAutoComplete'])->name('citiesAutoComplete');


Route::group(['middleware' => 'auth:user'], static function () {
    Route::group(['prefix' => 'equipments', 'as' => 'equipments.'], static function () {
        Route::get('/',             [EquipmentController::class, 'index'])->name('index');
        Route::get('/create',       [EquipmentController::class, 'create'])->name('create');
        Route::get('/{equipment}' , [EquipmentController::class, 'show'])->name('show');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], static function () {
        Route::post('/',                      [CartController::class, 'addToCart'])->name('addToCart');
        Route::get('/',                       [CartController::class, 'index'])->name('index');
        Route::get('/deleteItem/{equipment}', [CartController::class, 'deleteItem'])->name('deleteItem');
    });

    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], static function () {
        Route::get('/',  [CheckoutController::class, 'proceedToCheckout'])->name('index');
        Route::get('/completeCheckoutAction',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeCheckoutAction');
        Route::get('/completeToCheckout',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeToCheckout');
    });
    Route::get('/invoice/{orderId}', [OrderController::class, 'showInvoice'])->name('invoice.show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Models\Equipment;
use App\Models\User;
use App\Repositories\CartRepository;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:web'], static function () {
    require_once base_path('routes/admin.php');
});

Route::group(['prefix' => 'user', 'as' => 'user.'], static function () {
    require_once base_path('routes/user.php');
});

Route::get('/change-lang',     [HomeController::class, 'changeLang'])->name('change-lang');

Route::get('/',                [HomeController::class, 'index'])->name('user.home');

Route::get('/get-shift-times', [EquipmentController::class, 'getShiftTimes']);

Route::get('/test', static function () {

    $startDate = '2023-01-01';
    $endDate = '2023-01-07';
    $shiftsPerDay = 3;

    $equipment = Equipment::find(1);
    $user = User::find(1);
    $cart = (new CartRepository())->getUserCart(1);

    $equipmentCartItem = $cart->items()->where('equipment_id', $equipment->id)->first();
    $equipmentShiftIds = $equipment->shifts()->pluck('shifts.id')->toArray();
    $userShiftIds      = $user->shifts()->pluck('shifts.id')->toArray();
    $userEquipmentIds  = $user->shifts()->wherePivot('equipment_id', $equipment->id)->pluck('shifts.id')->toArray();

    return json_decode(json_encode(geAdminShifts()));
    return $equipment->shifts;
    $start = Carbon::parse($startDate);
    $end = Carbon::parse($endDate);
    $allShifts = [];

    // Define time slots for each shift (example: 8-hour shifts)
    $shiftDuration = 24 / $shiftsPerDay;

    while ($start->lte($end)) {
        for ($i = 0; $i < $shiftsPerDay; $i++) {
            $shiftStart = $start->copy()->addHours($i * $shiftDuration);
            $shiftEnd = $shiftStart->copy()->addHours($shiftDuration);

            $allShifts[] = [
                'date' => $start->toDateString(),
                'shift_number' => $i + 1,
                'shift_start' => $shiftStart->format('Y-m-d H:i'),
                'shift_end' => $shiftEnd->format('Y-m-d H:i')
            ];
        }
        $start->addDay();
    }

    return $allShifts;
});

Route::get('new-design-homepage', static function () {
    return view('frontend.pages.new.home');
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Admin/EquipmentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\EquipmentRequest;
use App\Models\Equipment;
use App\Models\Product;
use App\Repositories\EquipmentRepository;
use App\Services\DatatableService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;


class EquipmentController extends Controller
{
    public string $resource = 'equipments';
    private EquipmentRepository $equipmentRepository;
    public function __construct(EquipmentRepository $equipmentRepository)
    {
        appendGeneralPermissions($this);
        $this->equipmentRepository = $equipmentRepository;
        view()->share('item', 'equipment');
        view()->share('class', Equipment::class);
    }
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('admin.crud.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.crud.edit-new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param EquipmentRequest $request
     * @return RedirectResponse
     */
    public function store(EquipmentRequest $request): RedirectResponse
    {
        $this->equipmentRepository->add($request);

        $request->session()->flash('success', 'Equipment created successfully');

        if ($request->has('add-new')) {
            return redirect()->route('admin.equipment.create');
        }

        return redirect()->route('admin.equipment.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Equipment $equipment
     * @return Factory|View
     */
    public function show(Equipment $equipment)
    {
        return view('admin.equipment.show', compact('equipment'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Equipment $equipment
     * @return Application|Factory|View
     */
    public function edit(Equipment $equipment)
    {
        return view('admin.crud.edit-new', ['equipment' => $equipment]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param EquipmentRequest $request
     * @param Equipment $equipment
     * @return RedirectResponse
     */
    public function update(EquipmentRequest $request, Equipment $equipment): RedirectResponse
    {
        $this->equipmentRepository->update($request, $equipment);

        $request->session()->flash('success', 'Equipment updated successfully');

        if ($request->has('add-new')) {
            return redirect()->back();
        }

        return redirect()->route('admin.equipment.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param Equipment $equipment
     * @return RedirectResponse
     */
    public function destroy(Request $request, Equipment $equipment): RedirectResponse
    {
        $this->equipmentRepository->delete($equipment);
        $request->session()->flash('success', 'Equipment deleted successfully');
        return redirect()->route('admin.equipment.index');
    }

    /**
     * Retries the resources from storage.
     *
     * @param Request $request
     * @param EquipmentRepository $equipmentRepository
     * @return JsonResponse
     */
    public function getEquipments(Request $request, EquipmentRepository $equipmentRepository): JsonResponse
    {
        $equipments = $equipmentRepository->getEquipmentDataTable($request);
        return response()->json(DatatableService::equipmentDatatable($equipments));
    }

    public function removeImage(Request $request): string
    {
        $item = Equipment::query()->find($request->get('id'));
        $images = [];
        foreach ($item->images as $image) {
            if ($image == $request->get('image')) {
                Storage::disk('public')->delete($image);
            } else {
                $images[] = $image;
            }
        }
        $item->images = $images;
        $item->save();

        return 'image removed successfully';
    }
}

app/Http/Controllers/Frontend/EquipmentController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Equipment;
use App\Models\Shift;
use App\Repositories\EquipmentRepository;
use Carbon\Carbon;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class EquipmentController extends Controller
{
    private $equipmentRepository;

    public function __construct(EquipmentRepository $equipmentRepository)
    {
        $this->equipmentRepository = $equipmentRepository;
    }

    /**
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('frontend.pages.equipment.create');
    }

    /**
     * @param Request $request
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $equipments = $this->equipmentRepository->getEquipments($request)->paginate(8);
        return view('frontend.pages.equipment.index', compact('equipments',));
    }

    /**
     * @param Equipment $equipment
     * @param Request $request
     * @return Application|Factory|View
     */
    public function show(Equipment $equipment, Request $request)
    {
        $request->request->add(['admin_id' => $equipment->admin_id ?? null]);
        $recommendedEquipments = $this->equipmentRepository->getEquipments($request)->where('category_id', $equipment->category_id)->take(4)->get();
        return view('frontend.pages.equipment.show', compact('equipment', 'recommendedEquipments'));
    }


    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function getShiftTimes(Request $request): JsonResponse
    {
        $shiftIds = $request->get('id');
        $shifts = Shift::whereIn('id', $shiftIds)->active()->orderBy('start_date')->get();

        if ($shifts->isEmpty()) {
            return response()->json(['status' => 'error', 'message' => 'Shift not found'], 404);
        }

        $data = $shifts->flatMap(function ($shift) {
            $formattedDate = Carbon::parse($shift->start_date)->format('m-d');
            return Shift::whereRaw('DATE_FORMAT(start_date, "%m-%d") = ?', [$formattedDate])
                ->active()
                ->get();
        })->map(function ($item) {
            return [
                'id'           => $item->id,
                'start_period' => Carbon::parse($item->start_date)->format('H:i'),
                'date'         => Carbon::parse($item->start_date)->format('m-d H:i'),
                'end_period'   => Carbon::parse($item->end_date)->format('H:i'),
                'full_date'    => Carbon::parse($item->start_date)->format('m-d H:i') . ' => ' . Carbon::parse($item->end_date)->format('H:i')
            ];
        });
        $times = collect($data);
        $html = view('frontend.components.u-select-period', compact('times'))->render();
        return response()->json(['html' => $html, 'data' => $data]);
    }
}

resources/views/frontend/pages/equipment/create.blade.php
<x-u-master>

<div class="container mt-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Equipments</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create</li>
        </ol>
    </nav>
    <h2>Basic equipment info</h2>
    <br>
    <form>
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="type">Type</label>
                <input type="text" class="form-control" id="type">
            </div>
            <div class="form-group col-md-4">
                <label for="productionDate">Production Date</label>
                <input type="text" class="form-control" id="productionDate">
            </div>
            <div class="form-group col-md-4">
                <label for="model">Model</label>
                <input type="text" class="form-control" id="model">
            </div>
        </div>
        <!-- Add other form fields similar to the above structure -->

        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="manufacturer">Manufacturer</label>
                <input type="text" class="form-control" id="manufacturer">
            </div>
            <div class="form-group col-md-4">
                <label for="licensePlate">License Plate</label>
                <input type="text" class="form-control" id="licensePlate">
            </div>
            <div class="form-group col-md-4">
                <label for="registrationNumber">Registration Number</label>
                <input type="text" class="form-control" id="registrationNumber">
            </div>
        </div>
        <!-- Continue adding the rest of the fields in a similar manner -->

        <div class="form-row mt-3">
            <div class="col-md-4">
                <div class="upload-box">
                    <img  src="placeholder-image.png" class="img-fluid" alt="Upload">
                </div>
            </div>
            <div class="col-md-4">
                <div class="upload-box">
                    <img  src="placeholder-image.png" class="img-fluid" alt="Upload">
                </div>
            </div>
            <div class="col-md-4">
                <div class="upload-box">
                    <img  src="placeholder-image.png" class="img-fluid" alt="Upload">
                </div>
            </div>
        </div>

        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-warning mt-4">Create Equipment</button>
        </div>
    </form>
</div>
</x-u-master>

resources/views/frontend/pages/equipment/index.blade.php
<x-u-master :title="__('frontend.home')">
    @section('styles')
        <style>

            .card-img-top {
                height: 50px;
                object-fit: cover;
            }
        </style>
    @endsection

    <!-- Main Content -->
    <div class="container my-5">
        <h1 class="mb-4">Equipments</h1>
        <div class="row">
            @foreach($equipments as $equipment)
                <!-- Equipment Item -->
                <div class="col-md-3 mb-4 box">
                    <a href="{{route('user.equipments.show' ,$equipment )}}" class="card">
                        <img src="{{storageImage($equipment->images[0] ?? '')}}"
                             height="250" width="250"
                             onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"
                             class="card-img-top" alt="{{$equipment->name}}">
                        <div class="card-body">
                            <h5 class="card-title">{{$equipment->name}}</h5>
                            <p class="card-text">{{$equipment->count}} Unit</p>
                        </div>
                    </a>
                </div>
                <!-- Repeat Equipment Item as needed -->
            @endforeach
        </div>
        <div class="row mb-4 d-flex justify-content-center">
            {{$equipments->links()}}
        </div>
    </div>
</x-u-master>

resources/views/frontend/pages/equipment/show.blade.php
<x-u-master>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{route('user.home')}}">Home</a></li>
                <li class="breadcrumb-item"><a href="{{route('user.equipments.index')}}">Equipment</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{$equipment->name}}</li>
            </ol>
        </nav>
        <div class="box">
            <div class="row">
                <div class="col-md-6 main-image">
                    <img src="{{storageImage($equipment->images[0] ?? '')}}"
                         height="520" width="300"
                         onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"
                         alt="{{$equipment->name}}">

                    @if($equipment->images && count($equipment->images) > 2)
                        <div class="image-gallery mt-3">
                            @foreach($equipment->images as $image)
                                @if($loop->index !== 0)
                                    <img src="{{storageImage($image)}}" style="height: 100px; width: 100px"
                                         onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"
                                         alt="Thumbnail {{$loop->index}}">
                                @endif
                            @endforeach
                        </div>
                    @endif
                </div>
                <div class="col-md-6">
                    <h3>{{$equipment->name}}</h3>
                    <form method="POST" action="{{route('user.cart.addToCart')}}">
                        @csrf
                        <div class="row">
                            <div class="form-group col-6">
                                <label for="reference_name">Reference Name</label>
                                <input type="text" class="form-control"
                                       id="reference_name"
                                       name="reference_name"
                                       value="{{$equipment->reference_name ?? ''}}"
                                       readonly>
                            </div>
                            <div class="form-group col-6">
                                <label for="type">Type</label>
                                <input type="text"
                                       class="form-control"
                                       readonly
                                       id="type"
                                       value="{{$equipment->category->name ?? __('frontend.no_category')}}">
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-6">
                                <label for="production_year">Production Year</label>
                                <input type="text" class="form-control"
                                       id="production_year"
                                       name="production_year"
                                       value="{{$equipment->production_year ?? ''}}"
                                       readonly>
                            </div>
                            <input type="hidden" name="equipment_id" id="equipment_id" value="{{$equipment->id}}"/>
                            <div class="form-group col-6">
                                <label for="quantity">Quantity</label>
                                <input type="number" class="form-control" id="quantity" name="quantity" value="1"
                                       max="{{$equipment->count}}"
                                       min="1">
                            </div>
                        </div>
                        @if(count($equipment->shifts) !== 0)
                            <div class="row">
                                <div class="form-group col-12">
                                    <label for="reservation_start">Reservation date</label>
                                    <select class="form-control select2 w-100" multiple name="reservation_start[]"
                                            id="reservation_start">
                                        <option value="" disabled>Select date</option>
                                        @foreach($equipment->shifts as $index => $item)
                                            <option value="{{$item->id ?? '' }}">
                                                {{ $item->date }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="row d-none time-picker">
                                <div class="form-group col-12">
                                    <label for="full_date[]">First Shift Start</label>
                                    <select class="form-control select2 w-100" multiple name="full_date[]"
                                            id="full_date">
                                        <option value="" disabled>Select time</option>
                                    </select>
                                </div>
                            </div>
                        @else
                            <div class="row">
                                <div class="col-12 text-center text-danger">
                                    <h3>{{__('frontend.not_available_shifts')}}</h3>
                                </div>
                            </div>
                        @endif

                        <div class="form-check mb-3">
                            <input type="checkbox" {{ $equipment->isPrivate === 1 ? "checked" :'' }}  readonly
                                   class="form-check-input" id="privateProject" name="private">
                            <label class="form-check-label" for="privateProject">Private Project</label>
                        </div>

                        <div class="form-check mb-3">
                            <input type="checkbox" {{ $equipment->withDriver === 1 ? "checked" :'' }} readonly
                                   class="form-check-input" id="withDriver" name="withDriver">
                            <label class="form-check-label" for="withDriver">With driver</label>
                        </div>

                        <button type="submit" class="btn btn-color w-100">Book</button>
                        <div class="d-flex">
                            <p class="mt-3">Cash On Delivery Fees: 00 SR | Shipping Fees: 00 SR | Address: If inside
                                WEWA</p>
                            <p class="mt-3"> Delivered Within: 3 working days | Delivery Note: Order May get delayed</p>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="related-units mt-5">
            <h4>Related Units</h4>
            <div class="row">
                @foreach($recommendedEquipments as $equipment)
                    <!-- Equipment Item -->
                    <div class="col-md-3 mb-4 box ">
                        <a href="{{route('user.equipments.show' ,$equipment )}}" class="card">
                            <img src="{{storageImage($equipment->images[0] ?? '')}}"
                                 onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"
                                 class="card-img-top" alt="{{$equipment->name}}">
                            <div class="card-body">
                                <h5 class="card-title">{{$equipment->name}}</h5>
                                <p class="card-text">{{$equipment->count}} Unit</p>
                            </div>
                        </a>
                    </div>
                    <!-- Repeat Equipment Item as needed -->
                @endforeach
            </div>

        </div>
    </div>
    @section('scripts')
        <script type="text/javascript" src="{{asset('js/frontend/booking.js')}}"></script>
    @endsection
</x-u-master>