routes/admin.php
<?php


use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\EquipmentController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShiftController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

// GENERAL & AUTOCOMPLETE ROUTES
Route::get('/',                  [HomeController::class, 'dashboard'])
    ->name('dashboard');

Route::get('/search',            [HomeController::class, 'search'])
    ->name('search');

Route::post('/create-shift',       [ShiftController::class, 'create-shift'])->name('create-shift');

Route::get('/usersAutoComplete',    [UserController::class, 'usersAutoComplete'])
    ->name('usersAutoComplete');

Route::get('/citiesAutoComplete',   [CityController::class, 'citiesAutoComplete'])
    ->name('citiesAutoComplete');

Route::get('/supplierAutoComplete', [AdminController::class, 'supplierAutoComplete'])
    ->name('supplierAutoComplete');

Route::get('remove-images',         [EquipmentController::class, 'removeImage'])->name('removeImage');

Route::prefix('datatables')->name('datatables.')->group(function () {

    Route::post('/getEquipments',   [EquipmentController::class, 'getEquipments'])
        ->name('getEquipments');

    Route::post('/getAdmins',       [AdminController::class, 'getAdmins'])
        ->name('getAdmins');

    Route::post('/getCategories',   [CategoryController::class, 'getCategories'])
        ->name('getCategories');

    Route::post('/getShifts',        [ShiftController::class, 'getShifts'])
        ->name('getShifts');

    Route::post('/getContacts',     [ContactController::class, 'getContacts'])
        ->name('getContacts');

    Route::post('/getUsers',        [UserController::class, 'getUsers'])
        ->name('getUsers');

    Route::post('/getCities',       [CityController::class, 'getCities'])
        ->name('getCities');

    Route::GET('/setStatus/{order}',[AdminController::class, 'setStatus'])
        ->name('setStatus');
});

Route::prefix('orders')->name('orders.')->group(function (){
    Route::POST('/getOrders',            [OrderController::class, 'getOrders'])->name('getOrders');
    Route::GET('/',                      [OrderController::class, 'index'])->name('index');
    Route::GET('/{order}',               [OrderController::class, 'show'])->name('show');
    Route::GET('/setOrderStatus/{id}',   [OrderController::class, 'setOrderStatus'])->name('setOrderStatus');
    Route::GET('/setOrderBranch/{order}',[OrderController::class, 'setOrderBranch'])->name('setOrderBranch');
});

Route::resource('settings',       SettingController::class);
Route::resource('categories',     CategoryController::class);
Route::resource('users',          UserController::class);
Route::resource('orders',         OrderController::class);
Route::resource('shifts',         ShiftController::class);
Route::resource('admins',         AdminController::class);
Route::resource('cities',         CityController::class);
Route::resource('roles',          RoleController::class);
Route::resource('equipment',      EquipmentController::class);
Route::resource('contacts',       ContactController::class);

routes/user.php
<?php


use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
|
| Here is where you can register user routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "user" middleware group. Now create something great!
|
*/
// GENERAL
Route::get('/citiesAutoComplete', [HomeController::class, 'citiesAutoComplete'])->name('citiesAutoComplete');


Route::group(['middleware' => 'auth:user'], static function () {
    Route::group(['prefix' => 'equipments', 'as' => 'equipments.'], static function () {
        Route::get('/',             [EquipmentController::class, 'index'])->name('index');
        Route::get('/create',       [EquipmentController::class, 'create'])->name('create');
        Route::get('/{equipment}' , [EquipmentController::class, 'show'])->name('show');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], static function () {
        Route::post('/',                      [CartController::class, 'addToCart'])->name('addToCart');
        Route::get('/',                       [CartController::class, 'index'])->name('index');
        Route::get('/deleteItem/{equipment}', [CartController::class, 'deleteItem'])->name('deleteItem');
    });

    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], static function () {
        Route::get('/',  [CheckoutController::class, 'proceedToCheckout'])->name('index');
        Route::get('/completeCheckoutAction',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeCheckoutAction');
        Route::get('/completeToCheckout',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeToCheckout');
    });
    Route::get('/invoice/{orderId}', [OrderController::class, 'showInvoice'])->name('invoice.show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Models\Equipment;
use App\Models\User;
use App\Repositories\CartRepository;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:web'], static function () {
    require_once base_path('routes/admin.php');
});

Route::group(['prefix' => 'user', 'as' => 'user.'], static function () {
    require_once base_path('routes/user.php');
});

Route::get('/change-lang',     [HomeController::class, 'changeLang'])->name('change-lang');

Route::get('/',                [HomeController::class, 'index'])->name('user.home');

Route::get('/get-shift-times', [EquipmentController::class, 'getShiftTimes']);

Route::get('/test', static function () {

    $startDate = '2023-01-01';
    $endDate = '2023-01-07';
    $shiftsPerDay = 3;

    $equipment = Equipment::find(1);
    $user = User::find(1);
    $cart = (new CartRepository())->getUserCart(1);

    $equipmentCartItem = $cart->items()->where('equipment_id', $equipment->id)->first();
    $equipmentShiftIds = $equipment->shifts()->pluck('shifts.id')->toArray();
    $userShiftIds      = $user->shifts()->pluck('shifts.id')->toArray();
    $userEquipmentIds  = $user->shifts()->wherePivot('equipment_id', $equipment->id)->pluck('shifts.id')->toArray();

    return json_decode(json_encode(geAdminShifts()));
    return $equipment->shifts;
    $start = Carbon::parse($startDate);
    $end = Carbon::parse($endDate);
    $allShifts = [];

    // Define time slots for each shift (example: 8-hour shifts)
    $shiftDuration = 24 / $shiftsPerDay;

    while ($start->lte($end)) {
        for ($i = 0; $i < $shiftsPerDay; $i++) {
            $shiftStart = $start->copy()->addHours($i * $shiftDuration);
            $shiftEnd = $shiftStart->copy()->addHours($shiftDuration);

            $allShifts[] = [
                'date' => $start->toDateString(),
                'shift_number' => $i + 1,
                'shift_start' => $shiftStart->format('Y-m-d H:i'),
                'shift_end' => $shiftEnd->format('Y-m-d H:i')
            ];
        }
        $start->addDay();
    }

    return $allShifts;
});

Route::get('new-design-homepage', static function () {
    return view('frontend.pages.new.home');
});

require __DIR__ . '/auth.php';

resources/views/admin/layouts/base/_aside.blade.php
<div class="aside aside-left d-flex flex-column flex-row-auto" id="kt_aside">
    <!--begin::Aside Menu-->
    <div class="aside-menu-wrapper flex-column-fluid" id="kt_aside_menu_wrapper">
        <!--begin::Menu Container-->
        <div id="kt_aside_menu" class="aside-menu min-h-lg-800px" data-menu-vertical="1" data-menu-scroll="1" data-menu-dropdown-timeout="500">
            <!--begin::Menu Nav-->
            <ul class="menu-nav">
                {{ renderHorMenu(config('menu_aside.items')) }}
            </ul>
            <!--end::Menu Nav-->
        </div>
        <!--end::Menu Container-->
    </div>
    <!--end::Aside Menu-->
</div>

resources/views/admin/layouts/base/_breadcrumb.blade.php
<!--begin::Subheader-->
<div class="subheader py-3 py-lg-8 subheader-transparent" id="kt_subheader">
    <div class="container d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">
            <!--begin::Page Heading-->
            <div class="d-flex align-items-baseline mr-5">
                <!--begin::Breadcrumb-->
                <ul class="breadcrumb breadcrumb-transparent breadcrumb-dot font-weight-bold my-2 p-0">
                    <li class="breadcrumb-item">
                        <a href="{{ route('admin.dashboard') }}" class="text-dark">{{ __('admin.home') }}</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="{{ action("App\Http\Controllers\Admin\\".toTitle($item)."Controller@index") }}" class="text-muted">{{ __('admin.'.plural($item)) }}</a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#" class="active">{{ __('admin.'.$item) }}</a>
                    </li>
                </ul>
                <!--end::Breadcrumb-->
            </div>
            <!--end::Page Heading-->
        </div>
        <!--end::Info-->
    </div>
</div>
<!--end::Subheader-->

resources/views/admin/layouts/base/_footer.blade.php
{{-- 
<div class="footer bg-white py-4 d-flex flex-lg-column" id="kt_footer">
    <!--begin::Container-->
    <div class="container d-flex flex-column flex-md-row align-items-center justify-content-between">
        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted font-weight-bold mr-2">2021©</span>
            <a href="http://octopus.com" target="_blank" class="text-dark-75 text-hover-primary">Octopus</a>
        </div>
        <!--end::Copyright-->
        <!--begin::Nav-->
        <div class="nav nav-dark order-1 order-md-2">
            <a href="#" target="_blank" class="nav-link pr-3 pl-0">About</a>
            <a href="#" target="_blank" class="nav-link px-3">Team</a>
            <a href="#" target="_blank" class="nav-link pl-3 pr-0">Contact</a>
        </div>
        <!--end::Nav-->
    </div>
    <!--end::Container-->
</div> --}}

resources/views/admin/layouts/base/_header-mobile.blade.php
<div id="kt_header_mobile" class="header-mobile header-mobile-fixed">
    <!--begin::Logo-->
    <a href="#">
        <img onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"  alt="Logo" src="{{ asset('assets/media/logos/logo-letter-1.png') }}" class="logo-default max-h-30px" />
    </a>
    <!--end::Logo-->
    <!--begin::Toolbar-->
    <div class="d-flex align-items-center">
        <button class="btn p-0 burger-icon rounded-0 burger-icon-left" id="kt_aside_tablet_and_mobile_toggle">
            <span></span>
        </button>
        <button class="btn btn-hover-text-primary p-0 ml-3" id="kt_header_mobile_topbar_toggle">
                <span class="svg-icon svg-icon-xl">
                    <!--begin::Svg Icon | path:assets/media/svg/icons/General/User.svg-->
                    {{ getSVG('media/svg/icons/General/User.svg') }}
                    <!--end::Svg Icon-->
                </span>
        </button>
    </div>
    <!--end::Toolbar-->
</div>

resources/views/admin/layouts/base/_header.blade.php
<div id="kt_header" class="header header-fixed">
    <!--begin::Container-->
    <div class="container d-flex align-items-stretch justify-content-between">
        <!--begin::Left-->
        <div class="d-none d-lg-flex align-items-center mr-3">
            <!--begin::Aside Toggle-->
            <button class="btn btn-icon aside-toggle ml-n3 mr-10" id="kt_aside_desktop_toggle">
                    <span class="svg-icon svg-icon-xxl svg-icon-dark-75">
                        {{ getSVG('assets/media/svg/icons/Text/Align-left.svg') }}
                    </span>
            </button>
            <!--end::Aside Toggle-->
            <!--begin::Logo-->
            <a href="{{ route('admin.dashboard') }}">
                {{-- <img onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"  alt="Logo" src="{{ asset('custom/logo-icon.png') }}" class="logo-sticky max-h-35px" /> --}}
            </a>
            <!--end::Logo-->
            <!--begin::Desktop Search-->
            <div class="quick-search quick-search-inline ml-20 w-300px" id="kt_quick_search_inline">
                <!--begin::Form-->
                <form method="get" class="quick-search-form">
                    <div class="input-group rounded bg-light">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <span class="svg-icon svg-icon-lg">
                                    {{ getSVG('assets/media/svg/icons/General/Search.svg') }}
                                </span>
                            </span>
                        </div>
                        <input type="text" class="form-control h-45px" placeholder="Search..." />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="quick-search-close ki ki-close icon-sm text-muted"></i>
                            </span>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
                <!--begin::Search Toggle-->
                <div id="kt_quick_search_toggle" data-toggle="dropdown" data-offset="0px,1px"></div>
                <!--end::Search Toggle-->
                <!--begin::Dropdown-->
                <div class="dropdown-menu dropdown-menu-left dropdown-menu-lg dropdown-menu-anim-up">
                    <div class="quick-search-wrapper scroll" data-scroll="true" data-height="350" data-mobile-height="200"></div>
                </div>
                <!--end::Dropdown-->
            </div>
            <!--end::Desktop Search-->
        </div>
        <!--end::Left-->
        <!--begin::Topbar-->
        @include('admin.layouts.base._topbar')
        <!--end::Topbar-->
    </div>
    <!--end::Container-->
</div>

resources/views/admin/layouts/base/_topbar.blade.php
<div class="topbar">
    <!--begin::Tablet & Mobile Search-->
    <div class="dropdown d-flex d-lg-none">
        <!--begin::Toggle-->
        <div class="topbar-item" data-toggle="dropdown" data-offset="10px,0px">
            <div class="btn btn-icon btn-clean btn-lg btn-dropdown mr-1">
                {{ getSVG("assets/media/svg/icons/General/Search.svg", "svg-icon-xl svg-icon-primary") }}
            </div>
        </div>
        <!--end::Toggle-->
        <!--begin::Dropdown-->
        <div class="dropdown-menu p-0 m-0 dropdown-menu-right dropdown-menu-anim-up dropdown-menu-lg">
            <div class="quick-search quick-search-dropdown" id="kt_quick_search_dropdown">
                <!--begin:Form-->
                <form method="get" action="#" class="quick-search-form">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            {{ getSVG("assets/media/svg/icons/General/Search.svg", "svg-icon-lg") }}
                        </div>
                        <input type="text" name="search" id="search" value="{{ $search ?? '' }}" class="form-control" placeholder="Search..." />
                        <div class="input-group-append">
                            <span class="input-group-text">
                                <i class="quick-search-close ki ki-close icon-sm text-muted"></i>
                            </span>
                        </div>
                    </div>
                </form>
                <!--end::Form-->
                <!--begin::Scroll-->
                <div class="quick-search-wrapper scroll" data-scroll="true" data-height="325" data-mobile-height="200"></div>
                <!--end::Scroll-->
            </div>
        </div>
        <!--end::Dropdown-->
    </div>
    <!--end::Tablet & Mobile Search-->
    <!--begin::Quick Actions-->
    @role('Admin')
    <div class="topbar-item mr-4">
        <div class="btn btn-icon btn-sm btn-clean btn-text-dark-75" id="kt_quick_actions_toggle">
            <span class="svg-icon svg-icon-lg">
                {{ getSVG("assets/media/svg/icons/Layout/Layout-4-blocks.svg", "svg-icon-lg") }}
            </span>
        </div>
    </div>
    @endrole
    <!--end::Quick panel-->
    <!--begin::User-->
    <div class="topbar-item mr-4">
        <div class="btn btn-icon btn-sm btn-clean btn-text-dark-75" id="kt_quick_user_toggle">
            <span class="svg-icon svg-icon-lg">
                {{ getSVG("assets/media/svg/icons/General/User.svg", "svg-icon-xl") }}
            </span>
        </div>
    </div>
    <!--end::User-->
</div>