routes/admin.php
<?php


use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\EquipmentController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShiftController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

// GENERAL & AUTOCOMPLETE ROUTES
Route::get('/',                  [HomeController::class, 'dashboard'])
    ->name('dashboard');

Route::get('/search',            [HomeController::class, 'search'])
    ->name('search');

Route::post('/create-shift',       [ShiftController::class, 'create-shift'])->name('create-shift');

Route::get('/usersAutoComplete',    [UserController::class, 'usersAutoComplete'])
    ->name('usersAutoComplete');

Route::get('/citiesAutoComplete',   [CityController::class, 'citiesAutoComplete'])
    ->name('citiesAutoComplete');

Route::get('/supplierAutoComplete', [AdminController::class, 'supplierAutoComplete'])
    ->name('supplierAutoComplete');

Route::get('remove-images',         [EquipmentController::class, 'removeImage'])->name('removeImage');

Route::prefix('datatables')->name('datatables.')->group(function () {

    Route::post('/getEquipments',   [EquipmentController::class, 'getEquipments'])
        ->name('getEquipments');

    Route::post('/getAdmins',       [AdminController::class, 'getAdmins'])
        ->name('getAdmins');

    Route::post('/getCategories',   [CategoryController::class, 'getCategories'])
        ->name('getCategories');

    Route::post('/getShifts',        [ShiftController::class, 'getShifts'])
        ->name('getShifts');

    Route::post('/getContacts',     [ContactController::class, 'getContacts'])
        ->name('getContacts');

    Route::post('/getUsers',        [UserController::class, 'getUsers'])
        ->name('getUsers');

    Route::post('/getCities',       [CityController::class, 'getCities'])
        ->name('getCities');

    Route::GET('/setStatus/{order}',[AdminController::class, 'setStatus'])
        ->name('setStatus');
});

Route::prefix('orders')->name('orders.')->group(function (){
    Route::POST('/getOrders',            [OrderController::class, 'getOrders'])->name('getOrders');
    Route::GET('/',                      [OrderController::class, 'index'])->name('index');
    Route::GET('/{order}',               [OrderController::class, 'show'])->name('show');
    Route::GET('/setOrderStatus/{id}',   [OrderController::class, 'setOrderStatus'])->name('setOrderStatus');
    Route::GET('/setOrderBranch/{order}',[OrderController::class, 'setOrderBranch'])->name('setOrderBranch');
});

Route::resource('settings',       SettingController::class);
Route::resource('categories',     CategoryController::class);
Route::resource('users',          UserController::class);
Route::resource('orders',         OrderController::class);
Route::resource('shifts',         ShiftController::class);
Route::resource('admins',         AdminController::class);
Route::resource('cities',         CityController::class);
Route::resource('roles',          RoleController::class);
Route::resource('equipment',      EquipmentController::class);
Route::resource('contacts',       ContactController::class);

routes/user.php
<?php


use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
|
| Here is where you can register user routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "user" middleware group. Now create something great!
|
*/
// GENERAL
Route::get('/citiesAutoComplete', [HomeController::class, 'citiesAutoComplete'])->name('citiesAutoComplete');


Route::group(['middleware' => 'auth:user'], static function () {
    Route::group(['prefix' => 'equipments', 'as' => 'equipments.'], static function () {
        Route::get('/',             [EquipmentController::class, 'index'])->name('index');
        Route::get('/create',       [EquipmentController::class, 'create'])->name('create');
        Route::get('/{equipment}' , [EquipmentController::class, 'show'])->name('show');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], static function () {
        Route::post('/',                      [CartController::class, 'addToCart'])->name('addToCart');
        Route::get('/',                       [CartController::class, 'index'])->name('index');
        Route::get('/deleteItem/{equipment}', [CartController::class, 'deleteItem'])->name('deleteItem');
    });

    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], static function () {
        Route::get('/',  [CheckoutController::class, 'proceedToCheckout'])->name('index');
        Route::get('/completeCheckoutAction',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeCheckoutAction');
        Route::get('/completeToCheckout',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeToCheckout');
    });
    Route::get('/invoice/{orderId}', [OrderController::class, 'showInvoice'])->name('invoice.show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Models\Equipment;
use App\Models\User;
use App\Repositories\CartRepository;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:web'], static function () {
    require_once base_path('routes/admin.php');
});

Route::group(['prefix' => 'user', 'as' => 'user.'], static function () {
    require_once base_path('routes/user.php');
});

Route::get('/change-lang',     [HomeController::class, 'changeLang'])->name('change-lang');

Route::get('/',                [HomeController::class, 'index'])->name('user.home');

Route::get('/get-shift-times', [EquipmentController::class, 'getShiftTimes']);

Route::get('/test', static function () {

    $startDate = '2023-01-01';
    $endDate = '2023-01-07';
    $shiftsPerDay = 3;

    $equipment = Equipment::find(1);
    $user = User::find(1);
    $cart = (new CartRepository())->getUserCart(1);

    $equipmentCartItem = $cart->items()->where('equipment_id', $equipment->id)->first();
    $equipmentShiftIds = $equipment->shifts()->pluck('shifts.id')->toArray();
    $userShiftIds      = $user->shifts()->pluck('shifts.id')->toArray();
    $userEquipmentIds  = $user->shifts()->wherePivot('equipment_id', $equipment->id)->pluck('shifts.id')->toArray();

    return json_decode(json_encode(geAdminShifts()));
    return $equipment->shifts;
    $start = Carbon::parse($startDate);
    $end = Carbon::parse($endDate);
    $allShifts = [];

    // Define time slots for each shift (example: 8-hour shifts)
    $shiftDuration = 24 / $shiftsPerDay;

    while ($start->lte($end)) {
        for ($i = 0; $i < $shiftsPerDay; $i++) {
            $shiftStart = $start->copy()->addHours($i * $shiftDuration);
            $shiftEnd = $shiftStart->copy()->addHours($shiftDuration);

            $allShifts[] = [
                'date' => $start->toDateString(),
                'shift_number' => $i + 1,
                'shift_start' => $shiftStart->format('Y-m-d H:i'),
                'shift_end' => $shiftEnd->format('Y-m-d H:i')
            ];
        }
        $start->addDay();
    }

    return $allShifts;
});

Route::get('new-design-homepage', static function () {
    return view('frontend.pages.new.home');
});

require __DIR__ . '/auth.php';

resources/views/admin/layouts/panels/_actions.blade.php
<div id="kt_quick_actions" class="offcanvas offcanvas-right p-10">
    <!--begin::Header-->
    <div class="offcanvas-header d-flex align-items-center justify-content-between pb-10">
        <h3 class="font-weight-bold m-0">{{ __('admin.quick_actions') }}
        <a href="#" class="btn btn-xs btn-icon btn-light btn-hover-primary" id="kt_quick_actions_close">
            <i class="ki ki-close icon-xs text-muted"></i>
        </a>
    </div>
    <!--end::Header-->
    <!--begin::Content-->
    <div class="offcanvas-content pr-5 mr-n5">
        @role('Admin')

        <div class="row gutter-b">
            <!--begin::Item-->
            <div class="col-6">
                <a href="{{ route('admin.settings.index') }}" class="btn btn-block btn-light btn-hover-primary text-dark-50 text-center py-10 px-5">
                    <span class="svg-icon svg-icon-3x svg-icon-primary m-0">
                        {{ getSVG("assets/media/svg/icons/Design/Color-profile.svg", "svg-icon-xl") }}
                    </span>
                    <span class="d-block font-weight-bold font-size-h6 mt-2">{{ __('admin.settings') }}</span>
                </a>
            </div>
            <!--end::Item-->
            <!--begin::Item-->
            <div class="col-6">
                <a href="{{ route('admin.users.index') }}" class="btn btn-block btn-light btn-hover-primary text-dark-50 text-center py-10 px-5">
                    <span class="svg-icon svg-icon-3x svg-icon-primary m-0">
                        {{ getSVG("assets/media/svg/icons/Communication/Group.svg", "svg-icon-xl") }}
                    </span>
                    <span class="d-block font-weight-bold font-size-h6 mt-2">{{ __('admin.users') }}</span>
                </a>
            </div>
            <!--end::Item-->
        </div>
        @endrole
    </div>
    <!--end::Content-->
</div>

resources/views/admin/layouts/panels/_alerts.blade.php
@if ($errors->any())
    <div class="alert alert-custom alert-primary shadow-lg fade show" role="alert">
        <div class="alert-icon"><i class="flaticon-warning"></i></div>
        <div class="alert-text">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
@endif
@if(Session::has('success'))
    <div class="alert alert-custom alert-success shadow-lg mt-3 fade show" role="alert">
        <div class="alert-icon"><i class="flaticon2-checkmark"></i></div>
        <div class="alert-text">{{ Session::get('success') }}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
@endif
@if(Session::has('warring'))
    <div class="alert alert-custom alert-warring shadow-lg mt-3 fade show" role="alert">
        <div class="alert-icon"><i class="flaticon2-checkmark"></i></div>
        <div class="alert-text">{{ Session::get('warring') }}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
@endif

@if(Session::has('error'))
    <div class="alert alert-custom alert-danger shadow-lg mt-3 fade show" role="alert">
        <div class="alert-icon"><i class="flaticon2-checkmark"></i></div>
        <div class="alert-text">{{ Session::get('error') }}</div>
        <div class="alert-close">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true"><i class="ki ki-close"></i></span>
            </button>
        </div>
    </div>
@endif

resources/views/admin/layouts/panels/_notifications.blade.php
<div id="kt_quick_notifications" class="offcanvas offcanvas-right p-10">
    <!--begin::Header-->
    <div class="offcanvas-header d-flex align-items-center justify-content-between mb-10">
        <h3 class="font-weight-bold m-0">Notifications
            <small class="text-muted font-size-sm ml-2">24 New</small></h3>
        <a href="#" class="btn btn-xs btn-icon btn-light btn-hover-primary" id="kt_quick_notifications_close">
            <i class="ki ki-close icon-xs text-muted"></i>
        </a>
    </div>
    <!--end::Header-->
    <!--begin::Content-->
    <div class="offcanvas-content pr-5 mr-n5">
        <!--begin::Nav-->
        <div class="navi navi-icon-circle navi-spacer-x-0">
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-bell text-success icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">5 new user generated report</div>
                        <div class="text-muted">Reports based on sales</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon2-box text-danger icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">2 new items submited</div>
                        <div class="text-muted">by Grog John</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-psd text-primary icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">79 PSD files generated</div>
                        <div class="text-muted">Reports based on sales</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon2-supermarket text-warning icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">$2900 worth producucts sold</div>
                        <div class="text-muted">Total 234 items</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-paper-plane-1 text-success icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">4.5h-avarage response time</div>
                        <div class="text-muted">Fostest is Barry</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-safe-shield-protection text-danger icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">3 Defence alerts</div>
                        <div class="text-muted">40% less alerts thar last week</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-notepad text-primary icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">Avarage 4 blog posts per author</div>
                        <div class="text-muted">Most posted 12 time</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-users-1 text-warning icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">16 authors joined last week</div>
                        <div class="text-muted">9 photodrapehrs, 7 designer</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon2-box text-info icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">2 new items have been submited</div>
                        <div class="text-muted">by Grog John</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon2-download text-success icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">2.8 GB-total downloads size</div>
                        <div class="text-muted">Mostly PSD end AL concepts</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon2-supermarket text-danger icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">$2900 worth producucts sold</div>
                        <div class="text-muted">Total 234 items</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-bell text-primary icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">7 new user generated report</div>
                        <div class="text-muted">Reports based on sales</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
            <!--begin::Item-->
            <a href="#" class="navi-item">
                <div class="navi-link rounded">
                    <div class="symbol symbol-50 symbol-circle mr-3">
                        <div class="symbol-label">
                            <i class="flaticon-paper-plane-1 text-success icon-lg"></i>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold font-size-lg">4.5h-avarage response time</div>
                        <div class="text-muted">Fostest is Barry</div>
                    </div>
                </div>
            </a>
            <!--end::Item-->
        </div>
        <!--end::Nav-->
    </div>
    <!--end::Content-->
</div>

resources/views/admin/layouts/panels/_product_options.blade.php
<div data-repeater-item="attribute" class="form-group row align-items-center">
    <div class="col-md-3">
        <label>{{ __('product.size') }}:</label>
        <select name="item_size" required class="form-control">
            <option value="">{{ __('product.empty') }}</option>
            @foreach($sizes as $size)
            <option id="{{$size->id}}" value="{{$size->id}}">{{$size->name}}</option>
            @endforeach
        </select>
        <div class="d-md-none mb-2"></div>
    </div>
    <div class="col-md-2">
        <label>{{ __('product.sort_order') }}:</label>
        <input required name="item_sort_order" type="number" min="0" step="any" class="form-control" />
        <div class="d-md-none mb-2"></div>
    </div>
    <div class="col-md-2">
        <label>{{ __('product.stock') }}:</label>
        <input required name="item_stock" type="number" min="0" step="any" class="form-control" />
        <div class="d-md-none mb-2"></div>
    </div>
    <div class="col-md-2">
        <label>{{ __('product.price') }}:</label>
        <input required name="item_price" type="number" min="0" step="any" class="form-control" />
        <div class="d-md-none mb-2"></div>
    </div>
    <div class="col-md-3" style="padding-top: 25px; padding-left: 25px;">
        <a href="javascript:;" data-repeater-delete="" class="btn btn-sm font-weight-bolder btn-light-danger">
            <i class="la la-trash-o"></i>{{ __('product.delete') }}</a>
        <div class="d-md-none mb-2"></div>
    </div>
</div>

resources/views/admin/layouts/panels/_profile.blade.php
<div id="kt_quick_user" class="offcanvas offcanvas-right p-10">
    <!--begin::Header-->
    <div class="offcanvas-header d-flex align-items-center justify-content-between pb-5">
        <h3 class="font-weight-bold m-0">{{ __('admin.admin_profile') }}
            <small class="text-muted font-size-sm ml-2">{{ __('admin.logged_admin') }}</small></h3>
        <a href="#" class="btn btn-xs btn-icon btn-light btn-hover-primary" id="kt_quick_user_close">
            <i class="ki ki-close icon-xs text-muted"></i>
        </a>
    </div>
    @php $admin = auth()->user() @endphp
    <!--end::Header-->

    <!--begin::Content-->
    <div class="offcanvas-content pr-5 mr-n5">
        <!--begin::Header-->
        <div class="d-flex align-items-center mt-5">
            <div class="symbol symbol-100 mr-5">
                <div class="symbol-label" style="background-image: url({{ $admin->avatar ? storageImage($admin->avatar) : asset('media/users/blank.png') }})"></div>
                <i class="symbol-badge bg-success"></i>
            </div>
            <div class="d-flex flex-column">
                <a href="#" class="font-weight-bold font-size-h5 text-dark-75 text-hover-primary">{{ $admin->name }}</a>
                <div class="text-muted mt-1">{{ $admin->username }}</div>
                <div class="navi mt-2">
                    <a href="#" class="navi-item">
                        <span class="navi-link p-0 pb-2">
                            <span class="navi-icon mr-1">
                                <span class="svg-icon svg-icon-lg svg-icon-primary">
                                        {{ getSVG("assets/media/svg/icons/Communication/Mail-notification.svg", "svg-icon-lg") }}
                                </span>
                            </span>
                            <span class="navi-text text-muted text-hover-primary">{{ $admin->email }}</span>
                        </span>
                    </a>
                    <form action="{{ route('logout') }}" method="post">
                        @csrf
                        <input type="submit" value="{{ __('admin.logout') }}" class="btn btn-sm btn-light-primary font-weight-bolder py-2 px-5">
                    </form>
                </div>
            </div>
        </div>
        <!--end::Header-->
        <!--begin::Separator-->
        <div class="separator separator-dashed mt-8 mb-5"></div>
        <!--end::Separator-->
        <!--begin::Nav-->
        <div class="navi navi-spacer-x-0 p-0">
            <!--begin::Item-->
            <a href="{{ route('admin.admins.edit', ['admin' => $admin]) }}" class="navi-item">
                <div class="navi-link">
                    <div class="symbol symbol-40 bg-light mr-3">
                        <div class="symbol-label">
                            <span class="svg-icon svg-icon-md svg-icon-success">
                                {{ getSVG("assets/media/svg/icons/General/Notification2.svg", "svg-icon-xl") }}
                            </span>
                        </div>
                    </div>
                    <div class="navi-text">
                        <div class="font-weight-bold">{{ __('admin.my_profile') }}</div>
                        <div class="text-muted">{{ __('admin.account_settings') }}
                            <span class="label label-light-danger label-inline font-weight-bold">{{ __('admin.update') }}</span></div>
                    </div>
                </div>
            </a>
            <!--end:Item-->
        </div>
        <!--end::Nav-->
        <!--begin::Separator-->
        <div class="separator separator-dashed my-7"></div>
        <!--end::Separator-->
    </div>
    <!--end::Content-->
</div>

resources/views/admin/layouts/panels/_scroll.blade.php
<div id="kt_scrolltop" class="scrolltop">
    <span class="svg-icon">
        {{ getSVG('assets/media/svg/icons/Navigation/Up-2.svg') }}
    </span>
</div>

resources/views/admin/layouts/panels/_search_item.blade.php
<div class="d-flex align-items-center flex-grow-1 mb-2">
    <div class="symbol symbol-30 bg-transparent flex-shrink-0">
        <img onerror="this.src='{{asset('assets/assets/images/no-image.jpg')}}';"  src="{{ $item->image ? storageImage($item->image) : asset('custom/logo-icon.png')}}" alt=""/>
    </div>
    <div class="d-flex flex-column ml-3 mt-2 mb-2">
        <a href="{{ $item->url }}" class="font-weight-bold text-dark text-hover-primary">
            {{ $item->name }}
        </a>
        <span class="font-size-sm font-weight-bold text-muted">
            {{ $item->class }}
        </span>
    </div>
</div>

resources/views/admin/layouts/panels/_sticky_toolbar.blade.php
<ul class="sticky-toolbar nav flex-column pl-2 pr-2 pt-3 pb-3 mt-4">
    <!--begin::Item-->
    <li class="nav-item mb-2"  data-toggle="tooltip" title="{{ __('admin.go_to_website') }}" data-placement="right">
{{--        <a class="btn btn-sm btn-icon btn-bg-light btn-text-success btn-hover-success" href="{{ route('home') }}">--}}
            <i class="flaticon2-drop"></i>
        </a>
    </li>
    <!--end::Item-->
    @role('Admin')
    <!--begin::Item-->
    <li class="nav-item mb-2" data-toggle="tooltip" title="{{ __('admin.go_to_settings') }}" data-placement="left">
        <a class="btn btn-sm btn-icon btn-bg-light btn-text-primary btn-hover-primary" href="{{ route('admin.settings.index') }}">
            <i class="flaticon2-gear"></i>
        </a>
    </li>
    <!--end::Item-->
    @endrole

</ul>