routes/admin.php
<?php


use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\EquipmentController;
use App\Http\Controllers\Admin\ContactController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\ShiftController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\RoleController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "admin" middleware group. Now create something great!
|
*/

// GENERAL & AUTOCOMPLETE ROUTES
Route::get('/',                  [HomeController::class, 'dashboard'])
    ->name('dashboard');

Route::get('/search',            [HomeController::class, 'search'])
    ->name('search');

Route::post('/create-shift',       [ShiftController::class, 'create-shift'])->name('create-shift');

Route::get('/usersAutoComplete',    [UserController::class, 'usersAutoComplete'])
    ->name('usersAutoComplete');

Route::get('/citiesAutoComplete',   [CityController::class, 'citiesAutoComplete'])
    ->name('citiesAutoComplete');

Route::get('/supplierAutoComplete', [AdminController::class, 'supplierAutoComplete'])
    ->name('supplierAutoComplete');

Route::get('remove-images',         [EquipmentController::class, 'removeImage'])->name('removeImage');

Route::prefix('datatables')->name('datatables.')->group(function () {

    Route::post('/getEquipments',   [EquipmentController::class, 'getEquipments'])
        ->name('getEquipments');

    Route::post('/getAdmins',       [AdminController::class, 'getAdmins'])
        ->name('getAdmins');

    Route::post('/getCategories',   [CategoryController::class, 'getCategories'])
        ->name('getCategories');

    Route::post('/getShifts',        [ShiftController::class, 'getShifts'])
        ->name('getShifts');

    Route::post('/getContacts',     [ContactController::class, 'getContacts'])
        ->name('getContacts');

    Route::post('/getUsers',        [UserController::class, 'getUsers'])
        ->name('getUsers');

    Route::post('/getCities',       [CityController::class, 'getCities'])
        ->name('getCities');

    Route::GET('/setStatus/{order}',[AdminController::class, 'setStatus'])
        ->name('setStatus');
});

Route::prefix('orders')->name('orders.')->group(function (){
    Route::POST('/getOrders',            [OrderController::class, 'getOrders'])->name('getOrders');
    Route::GET('/',                      [OrderController::class, 'index'])->name('index');
    Route::GET('/{order}',               [OrderController::class, 'show'])->name('show');
    Route::GET('/setOrderStatus/{id}',   [OrderController::class, 'setOrderStatus'])->name('setOrderStatus');
    Route::GET('/setOrderBranch/{order}',[OrderController::class, 'setOrderBranch'])->name('setOrderBranch');
});

Route::resource('settings',       SettingController::class);
Route::resource('categories',     CategoryController::class);
Route::resource('users',          UserController::class);
Route::resource('orders',         OrderController::class);
Route::resource('shifts',         ShiftController::class);
Route::resource('admins',         AdminController::class);
Route::resource('cities',         CityController::class);
Route::resource('roles',          RoleController::class);
Route::resource('equipment',      EquipmentController::class);
Route::resource('contacts',       ContactController::class);

routes/user.php
<?php


use App\Http\Controllers\Frontend\CartController;
use App\Http\Controllers\Frontend\CheckoutController;
use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Http\Controllers\Frontend\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| User Routes
|--------------------------------------------------------------------------
|
| Here is where you can register user routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "user" middleware group. Now create something great!
|
*/
// GENERAL
Route::get('/citiesAutoComplete', [HomeController::class, 'citiesAutoComplete'])->name('citiesAutoComplete');


Route::group(['middleware' => 'auth:user'], static function () {
    Route::group(['prefix' => 'equipments', 'as' => 'equipments.'], static function () {
        Route::get('/',             [EquipmentController::class, 'index'])->name('index');
        Route::get('/create',       [EquipmentController::class, 'create'])->name('create');
        Route::get('/{equipment}' , [EquipmentController::class, 'show'])->name('show');
    });

    Route::group(['prefix' => 'cart', 'as' => 'cart.'], static function () {
        Route::post('/',                      [CartController::class, 'addToCart'])->name('addToCart');
        Route::get('/',                       [CartController::class, 'index'])->name('index');
        Route::get('/deleteItem/{equipment}', [CartController::class, 'deleteItem'])->name('deleteItem');
    });

    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], static function () {
        Route::get('/',  [CheckoutController::class, 'proceedToCheckout'])->name('index');
        Route::get('/completeCheckoutAction',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeCheckoutAction');
        Route::get('/completeToCheckout',  [CheckoutController::class, 'completeCheckoutAction'])->name('completeToCheckout');
    });
    Route::get('/invoice/{orderId}', [OrderController::class, 'showInvoice'])->name('invoice.show');
});

routes/web.php
<?php

use App\Http\Controllers\Frontend\EquipmentController;
use App\Http\Controllers\Frontend\HomeController;
use App\Models\Equipment;
use App\Models\User;
use App\Repositories\CartRepository;
use Carbon\Carbon;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth:web'], static function () {
    require_once base_path('routes/admin.php');
});

Route::group(['prefix' => 'user', 'as' => 'user.'], static function () {
    require_once base_path('routes/user.php');
});

Route::get('/change-lang',     [HomeController::class, 'changeLang'])->name('change-lang');

Route::get('/',                [HomeController::class, 'index'])->name('user.home');

Route::get('/get-shift-times', [EquipmentController::class, 'getShiftTimes']);

Route::get('/test', static function () {

    $startDate = '2023-01-01';
    $endDate = '2023-01-07';
    $shiftsPerDay = 3;

    $equipment = Equipment::find(1);
    $user = User::find(1);
    $cart = (new CartRepository())->getUserCart(1);

    $equipmentCartItem = $cart->items()->where('equipment_id', $equipment->id)->first();
    $equipmentShiftIds = $equipment->shifts()->pluck('shifts.id')->toArray();
    $userShiftIds      = $user->shifts()->pluck('shifts.id')->toArray();
    $userEquipmentIds  = $user->shifts()->wherePivot('equipment_id', $equipment->id)->pluck('shifts.id')->toArray();

    return json_decode(json_encode(geAdminShifts()));
    return $equipment->shifts;
    $start = Carbon::parse($startDate);
    $end = Carbon::parse($endDate);
    $allShifts = [];

    // Define time slots for each shift (example: 8-hour shifts)
    $shiftDuration = 24 / $shiftsPerDay;

    while ($start->lte($end)) {
        for ($i = 0; $i < $shiftsPerDay; $i++) {
            $shiftStart = $start->copy()->addHours($i * $shiftDuration);
            $shiftEnd = $shiftStart->copy()->addHours($shiftDuration);

            $allShifts[] = [
                'date' => $start->toDateString(),
                'shift_number' => $i + 1,
                'shift_start' => $shiftStart->format('Y-m-d H:i'),
                'shift_end' => $shiftEnd->format('Y-m-d H:i')
            ];
        }
        $start->addDay();
    }

    return $allShifts;
});

Route::get('new-design-homepage', static function () {
    return view('frontend.pages.new.home');
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use App\Mail\ForgotMail;
use App\Mail\VerifyMail;
use Carbon\Carbon;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    public const TYPE_CONTACTOR = 'contractor';
    public const STATUS_INACTIVE = 0;
    public const STATUS_ACTIVE = 1;
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'company_name',
        'tax_number',
        'commercial_registration',
        'email',
        'password',
        'phone_number',
        'code',
        'token',
        'email_verified_at',
        'mobile_verified_at',
        'reset_token',
        'reset_verified',
        'status',
        'city_id',
    ];

    public $visibleAttributes = [
        'name' => 'text',
        'email' => 'text',
        'phone_number' => 'text',
        'status' => 'status',
    ];

    public $mediaAttributes = [
        'avatar' => 'image',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
        'mobile_verified_at' => 'datetime',
    ];
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
        'email_verified_at',
        'mobile_verified_at',
        'reset_token',
        'reset_verified',
        'status',
        'code',
        'app_notification_status',
        'created_at',
        'updated_at',
    ];


    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = Hash::make($value);
    }



    public function isActive(): bool
    {
        return $this->status;
    }


    public function city(): BelongsTo
    {
        return $this->belongsTo(City::class);
    }

    public function equipment(): BelongsToMany
    {
        return $this->belongsToMany(Equipment::class, 'equipment_shift_user', 'user_id', 'equipment_id')
            ->withPivot('shift_id')
            ->withTimestamps();
    }

    public function shifts(): BelongsToMany
    {
        return $this->belongsToMany(Shift::class, 'equipment_shift_user', 'user_id', 'shift_id')
            ->withPivot('equipment_id')
            ->withTimestamps();
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use App\Http\Traits\ActionsTrait;
use App\Models\User;
use App\Repositories\UserRepository;
use App\Services\DatatableService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class UserController extends Controller
{
    public string $resource = 'user';
    private UserRepository $userRepository;
    use ActionsTrait;

    public function __construct( UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
        appendGeneralPermissions($this);
        view()->share('item', $this->resource);
        view()->share('class', User::class);
    }

    /**
     * Display a listing of the resource.
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('admin.crud.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create()
    {
        return view('admin.crud.edit-new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param UserRequest $request
     * @return RedirectResponse
     */
    public function store(UserRequest $request): RedirectResponse
    {
        $this->userRepository->add($request);

        $request->session()->flash('success', 'user created successfully');

        if ($request->has('add-new')) {
            return redirect()->route('admin.users.create');
        }

        return redirect()->route('admin.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return Factory|\Illuminate\Contracts\View\View
     */
    public function show(User $user)
    {
        return view('admin.user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param User $user
     * @return Application|Factory|View
     */
    public function edit(User $user)
    {
        return view('admin.crud.edit-new', compact('user',));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UserRequest $request
     * @param User $user
     * @return RedirectResponse
     */
    public function update(UserRequest $request, User $user): RedirectResponse
    {
        $this->userRepository->update($request, $user);

        $request->session()->flash('success', 'user updated successfully');

        if ($request->has('add-new')) {
            return redirect()->back();
        }

        return redirect()->route('admin.users.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param User $user
     * @return RedirectResponse
     */
    public function destroy(Request $request, User $user): RedirectResponse
    {
        $this->userRepository->delete($user);
        $request->session()->flash('success', 'user deleted successfully');
        return redirect()->route('admin.users.index');
    }

    public function usersAutoComplete(Request $request): JsonResponse
    {
        $search = $request->get('search');
        $models = $this->userRepository->usersAutoComplete($search);

        return response()->json([
            'results' => $models
        ]);
    }

    public function getUsers(Request $request, UserRepository $userRepository): JsonResponse
    {
        $users = $userRepository->getUsersDataTable($request);
        return response()->json(DatatableService::userDatatable($users));
    }

    public function setStatus(Request $request, $id): string
    {
        $className = modelName($request->get('type') ?? 'user');
        $item = $className::find($id);
        $item->status = $request->get('status');
        $item->save();

        return "Edit Status Successfully";
    }

}

resources/views/admin/user/_form.blade.php
{{--Form Inputs--}}
@if($locale == 'en')
    <x-text :name="'name'" :locale="''" :oldValue="$entity ?? null" :required="true"></x-text>

    <x-email :name="'email'" :locale="''" :oldValue="$entity ?? null" :required="true"></x-email>

    <x-text :name="'phone_number'" :locale="''" :oldValue="$entity ?? null" :required="true"></x-text>

    <x-text :name="'company_name'" :locale="''" :oldValue="$entity ?? null" :required="false"></x-text>

    <x-text :name="'commercial_registration'" :locale="''" :oldValue="$entity ?? null" :required="false"></x-text>

    <x-text :name="'tax_number'" :locale="''" :oldValue="$entity ?? null" :required="false"></x-text>

    <x-password :name="'password'" :locale="''" :required="true"></x-password>

    <x-radio :name="'status'" :withLabel="true" :choices="getStatusVariables()" :oldValue="$entity ?? null"></x-radio>

    <x-select-ajax-data :name="'city_id'" url="{{route('admin.citiesAutoComplete')}}"
                        :displayName="'name'" :oldValue="isset($entity) ? $entity->city : null" >
    </x-select-ajax-data>

    <x-image :name="'image'" :locale="''" :oldValue="$entity ?? null"></x-image>

@endif

{{--End Form Inputs--}}

resources/views/admin/user/_gridFilter.blade.php
{{--Gird Filters--}}
<form action="{{ route('admin.'.plural($item).'.index') }}" method="GET">
    <div class="mb-7">
        <div class="row align-items-center">
            <div class="col-lg-11 col-xl-8">
                <div class="row align-items-center">
                    <div class="col-md-4 my-2 my-md-0">
                        <div class="input-icon">
                            <input type="text" name="search" id="kt_datatable_search_search" value="{{request()->query('search')}}" class="form-control" placeholder="{{ __('admin.search') }}..." />
                            <span>
								<i class="flaticon2-search-1 text-muted"></i>
							</span>
                        </div>
                    </div>
                    <div class="col-md-4 my-2 my-md-0">
                        <div class="d-flex align-items-center">
                            <label class="mr-3 mb-0 d-none d-md-block">{{ __('admin.status') }}:</label>
                            <select class="form-control" name="status" id="kt_datatable_search_status">
                                <option value="" {{( request()->query('status') === null ? 'selected' : '')}} > {{ __('admin.all') }} </option>
                                @foreach( getStatusVariables() as $status)
                                    <option value="{{ $status->value  }}" {{($status->value === request()->query('status')  && request()->query('status') !== null ? 'selected' : '')}}>
                                        {{ $status->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-1 mt-5 mt-lg-0">
                    <a style="white-space: nowrap;"  href="{{ route('admin.'.plural($item).'.index') }}" class="btn btn-light-primary px-6 font-weight-bold">{{ __('admin.reset') }}</a>
                </div>
            </div>
        </div>
    </div>
</form>
{{--End Gird Filters--}}

resources/views/admin/user/_scripts.blade.php
<script src="{{ asset('custom/js/jquery.validate.min.js') }}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key={{getGoogleMapKey()}}&loading=async&language=en&callback=initMap&libraries=geometry"></script>
<script src="{{ asset('js/users.js') }}"></script>

resources/views/admin/user/_table.blade.php
<!--begin::Advance Table Widget 3-->
<div class="card card-custom gutter-b shadow-lg mt-10">
    <!--begin::Header-->
    <div class="card-header border-0 py-5">
        <h3 class="card-title align-items-start flex-column">
            <span class="card-label font-weight-bolder text-dark">{{ __('admin.all_'.plural($item)) }}</span>
        </h3>
        @can('add '.plural($item))
            <div class="card-toolbar">
                <a href="{{ route('admin.'.plural($item).'.create') }}"
                   class="btn btn-primary font-weight-bolder font-size-sm">
                    <i class="fas fa-plus-circle"></i>{{ __('admin.new_'.$item) }}
                </a>
            </div>
        @endcan
    </div>
    <!--end::Header-->
    <!--begin::Body-->
    <div class="card-body pt-0 pb-3">
        <!--begin::Table-->
        <div class="">
            <table class="table table-checkable table-head-custom table-head-bg table-borderless table-vertical-center">
                @include('admin.'.$item.'._gridFilter')
                <div class="datatable datatable-bordered datatable-head-custom"
                     id="kt_datatable_users" data-locale="en" data-url="{{ route('admin.datatables.getUsers') }}">
                </div>
            </table>
        </div>
        <!--end::Table-->
    </div>
    <!--end::Body-->
</div>
<!--end::Advance Table Widget 3-->

resources/views/admin/user/show.blade.php
<x-master title="{{__('admin.show')}} {{ __('admin.'.$item) }}">

    @section('breadcrumb')
        @include('admin.layouts.base._breadcrumb', ['singular' => __('admin.'.$item), 'route' =>
        action("App\Http\Controllers\Admin\\".toTitle($item)."Controller@index"), 'plural' => __('admin.'.plural($item))])
    @endsection

    <!--begin::Container-->
    <div class="container">
        <!--begin::Dashboard-->
        <!--begin::Row-->
        <div class="row">
            <div class="col-xl-12">
                <h1 class="mt-10">{{ __('admin.show') }}
                    <code>{{ ${$item}->name }}</code> {{ __('admin.'.$item) }}
                </h1>
                <div class="card card-custom shadow-lg mt-10">
                    <!--begin::Card-->
                    <div class="card card-custom gutter-b">
                        <!--begin::Header-->
                        <!--end::Header-->
                        <div class="card-body px-0">
                            <div class="tab-content pt-5">
                                <div class="tab-pane active">
                                    <!--begin::Tab Content-->
                                    <div class="col-lg-12">
                                        <!--begin::Advance Table Widget 2-->
                                        <div class="card card-custom card-stretch gutter-b">
                                            <!--begin::Body-->
                                            <div class="card-body pt-3 pb-0">
                                                <div class="row">
                                                    <div class="col-xl-6">
                                                        <div
                                                            class="d-flex align-items-center mb-9 bg-light-secondary rounded p-5">
                                                            <div class="d-flex flex-column flex-grow-1 mr-2">
                                                                <a href="#"
                                                                   class="font-weight-bold text-dark-75 text-hover-primary font-size-lg mb-1">
                                                                    Name</a>
                                                                <span
                                                                    class="text-muted font-weight-bold user-name" >{{${$item}->name}}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-xl-6">
                                                        <div
                                                            class="d-flex align-items-center mb-9 bg-light-secondary rounded p-5">
                                                            <div class="d-flex flex-column flex-grow-1 mr-2">
                                                                <a href="#"
                                                                   class="font-weight-bold text-dark-75 text-hover-primary font-size-lg mb-1">Email</a>
                                                                <span
                                                                    class="text-muted font-weight-bold">{{${$item}->email}}</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                                <!--end::Body-->
                                            </div>
                                            <!--end::Advance Table Widget 2-->
                                            <div class="card-body pt-3 pb-0">
                                                <div class="col-md-12 row">
                                                    <h5>Map</h5>
                                                    <div class="card-body">
                                                        <input hidden name="user-id" type="text" value="{{${$item}->id}}" id="user-id">
                                                        <x-map   :longitude="${$item}->longitude ?? null"
                                                                 :latitude="${$item}->latitude ?? null" :hiddenInputs="false">
                                                        </x-map>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!--end::Tab Content-->
                                </div>
                                <div class="card-footer">
                                    <button onclick="window.history.back()" type="submit" class="btn btn-primary mr-2">
                                        <i class="ki ki-long-arrow-back icon-sm"></i>{{__('admin.back')}}
                                    </button>
                                </div>
                            </div>
                            <!--end::Body-->
                        </div>
                        <!--end::Card-->
                    </div>
                </div>
                <!--end::Row-->
                <!--begin::Row-->
            </div>
        </div>
    </div>
    <!--end::Container-->
    @section('scripts')
            <script src="https://maps.googleapis.com/maps/api/js?key={{getGoogleMapKey()}}&loading=async&language=en&callback=initMap"></script>
            <script src="{{ asset('js/bootstrap.js') }}"></script>
            <script src="{{ asset('js/users.js') }}"></script>
    @endsection
</x-master>